version: '3'
services:
  app:
    build: .
    container_name: neo4j-app
    depends_on:
      - neo4j
    environment:
      - NEO_HOSTNAME=neo4j
      - NEO_USERNAME=neo4j
      - NEO_PASSWORD=${NEO_PASSWORD}
      - APP_PORT=8080
      - GRPC_PORT=50051
    ports:
      - "8080:8080"
      - "50051:50051"

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "$HOME/neo4j/data:/data"
      - "$HOME/neo4j/logs:/logs"
