version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "$HOME/neo4j/data:/data"
      - "$HOME/neo4j/logs:/logs"
