// Code generated by protoc-gen-go. DO NOT EDIT.
// source: folder.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Folder struct {
	FolderID             string   `protobuf:"bytes,1,opt,name=folderID,proto3" json:"folderID,omitempty"`
	RevisionID           string   `protobuf:"bytes,2,opt,name=revisionID,proto3" json:"revisionID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ParentID             string   `protobuf:"bytes,4,opt,name=parentID,proto3" json:"parentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Folder) Reset()         { *m = Folder{} }
func (m *Folder) String() string { return proto.CompactTextString(m) }
func (*Folder) ProtoMessage()    {}
func (*Folder) Descriptor() ([]byte, []int) {
	return fileDescriptor_folder_1c0d2e0cd74b2487, []int{0}
}
func (m *Folder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Folder.Unmarshal(m, b)
}
func (m *Folder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Folder.Marshal(b, m, deterministic)
}
func (dst *Folder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Folder.Merge(dst, src)
}
func (m *Folder) XXX_Size() int {
	return xxx_messageInfo_Folder.Size(m)
}
func (m *Folder) XXX_DiscardUnknown() {
	xxx_messageInfo_Folder.DiscardUnknown(m)
}

var xxx_messageInfo_Folder proto.InternalMessageInfo

func (m *Folder) GetFolderID() string {
	if m != nil {
		return m.FolderID
	}
	return ""
}

func (m *Folder) GetRevisionID() string {
	if m != nil {
		return m.RevisionID
	}
	return ""
}

func (m *Folder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Folder) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

type FolderResponse struct {
	Folder               *Folder  `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FolderResponse) Reset()         { *m = FolderResponse{} }
func (m *FolderResponse) String() string { return proto.CompactTextString(m) }
func (*FolderResponse) ProtoMessage()    {}
func (*FolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_folder_1c0d2e0cd74b2487, []int{1}
}
func (m *FolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FolderResponse.Unmarshal(m, b)
}
func (m *FolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FolderResponse.Marshal(b, m, deterministic)
}
func (dst *FolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FolderResponse.Merge(dst, src)
}
func (m *FolderResponse) XXX_Size() int {
	return xxx_messageInfo_FolderResponse.Size(m)
}
func (m *FolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FolderResponse proto.InternalMessageInfo

func (m *FolderResponse) GetFolder() *Folder {
	if m != nil {
		return m.Folder
	}
	return nil
}

type CreateFolderRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	RevisionID           string   `protobuf:"bytes,2,opt,name=revisionID,proto3" json:"revisionID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ParentID             string   `protobuf:"bytes,4,opt,name=parentID,proto3" json:"parentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFolderRequest) Reset()         { *m = CreateFolderRequest{} }
func (m *CreateFolderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFolderRequest) ProtoMessage()    {}
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_folder_1c0d2e0cd74b2487, []int{2}
}
func (m *CreateFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFolderRequest.Unmarshal(m, b)
}
func (m *CreateFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFolderRequest.Marshal(b, m, deterministic)
}
func (dst *CreateFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFolderRequest.Merge(dst, src)
}
func (m *CreateFolderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFolderRequest.Size(m)
}
func (m *CreateFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFolderRequest proto.InternalMessageInfo

func (m *CreateFolderRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateFolderRequest) GetRevisionID() string {
	if m != nil {
		return m.RevisionID
	}
	return ""
}

func (m *CreateFolderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFolderRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

type GetFolderRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FolderID             string   `protobuf:"bytes,2,opt,name=folderID,proto3" json:"folderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFolderRequest) Reset()         { *m = GetFolderRequest{} }
func (m *GetFolderRequest) String() string { return proto.CompactTextString(m) }
func (*GetFolderRequest) ProtoMessage()    {}
func (*GetFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_folder_1c0d2e0cd74b2487, []int{3}
}
func (m *GetFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderRequest.Unmarshal(m, b)
}
func (m *GetFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderRequest.Marshal(b, m, deterministic)
}
func (dst *GetFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderRequest.Merge(dst, src)
}
func (m *GetFolderRequest) XXX_Size() int {
	return xxx_messageInfo_GetFolderRequest.Size(m)
}
func (m *GetFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderRequest proto.InternalMessageInfo

func (m *GetFolderRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetFolderRequest) GetFolderID() string {
	if m != nil {
		return m.FolderID
	}
	return ""
}

type UpdateFolderRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FolderID             string   `protobuf:"bytes,2,opt,name=folderID,proto3" json:"folderID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ParentID             string   `protobuf:"bytes,4,opt,name=parentID,proto3" json:"parentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFolderRequest) Reset()         { *m = UpdateFolderRequest{} }
func (m *UpdateFolderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFolderRequest) ProtoMessage()    {}
func (*UpdateFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_folder_1c0d2e0cd74b2487, []int{4}
}
func (m *UpdateFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFolderRequest.Unmarshal(m, b)
}
func (m *UpdateFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFolderRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFolderRequest.Merge(dst, src)
}
func (m *UpdateFolderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFolderRequest.Size(m)
}
func (m *UpdateFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFolderRequest proto.InternalMessageInfo

func (m *UpdateFolderRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UpdateFolderRequest) GetFolderID() string {
	if m != nil {
		return m.FolderID
	}
	return ""
}

func (m *UpdateFolderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateFolderRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

type DeleteFolderRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FolderID             string   `protobuf:"bytes,2,opt,name=folderID,proto3" json:"folderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFolderRequest) Reset()         { *m = DeleteFolderRequest{} }
func (m *DeleteFolderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFolderRequest) ProtoMessage()    {}
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_folder_1c0d2e0cd74b2487, []int{5}
}
func (m *DeleteFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFolderRequest.Unmarshal(m, b)
}
func (m *DeleteFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFolderRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFolderRequest.Merge(dst, src)
}
func (m *DeleteFolderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFolderRequest.Size(m)
}
func (m *DeleteFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFolderRequest proto.InternalMessageInfo

func (m *DeleteFolderRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *DeleteFolderRequest) GetFolderID() string {
	if m != nil {
		return m.FolderID
	}
	return ""
}

func init() {
	proto.RegisterType((*Folder)(nil), "pb.Folder")
	proto.RegisterType((*FolderResponse)(nil), "pb.FolderResponse")
	proto.RegisterType((*CreateFolderRequest)(nil), "pb.CreateFolderRequest")
	proto.RegisterType((*GetFolderRequest)(nil), "pb.GetFolderRequest")
	proto.RegisterType((*UpdateFolderRequest)(nil), "pb.UpdateFolderRequest")
	proto.RegisterType((*DeleteFolderRequest)(nil), "pb.DeleteFolderRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FolderServiceClient is the client API for FolderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FolderServiceClient interface {
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error)
	GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error)
	UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error)
	DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error)
}

type folderServiceClient struct {
	cc *grpc.ClientConn
}

func NewFolderServiceClient(cc *grpc.ClientConn) FolderServiceClient {
	return &folderServiceClient{cc}
}

func (c *folderServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error) {
	out := new(FolderResponse)
	err := c.cc.Invoke(ctx, "/pb.FolderService/CreateFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderServiceClient) GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error) {
	out := new(FolderResponse)
	err := c.cc.Invoke(ctx, "/pb.FolderService/GetFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderServiceClient) UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error) {
	out := new(FolderResponse)
	err := c.cc.Invoke(ctx, "/pb.FolderService/UpdateFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderServiceClient) DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*FolderResponse, error) {
	out := new(FolderResponse)
	err := c.cc.Invoke(ctx, "/pb.FolderService/DeleteFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FolderServiceServer is the server API for FolderService service.
type FolderServiceServer interface {
	CreateFolder(context.Context, *CreateFolderRequest) (*FolderResponse, error)
	GetFolder(context.Context, *GetFolderRequest) (*FolderResponse, error)
	UpdateFolder(context.Context, *UpdateFolderRequest) (*FolderResponse, error)
	DeleteFolder(context.Context, *DeleteFolderRequest) (*FolderResponse, error)
}

func RegisterFolderServiceServer(s *grpc.Server, srv FolderServiceServer) {
	s.RegisterService(&_FolderService_serviceDesc, srv)
}

func _FolderService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FolderServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FolderService/CreateFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FolderServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FolderService_GetFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FolderServiceServer).GetFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FolderService/GetFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FolderServiceServer).GetFolder(ctx, req.(*GetFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FolderService_UpdateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FolderServiceServer).UpdateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FolderService/UpdateFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FolderServiceServer).UpdateFolder(ctx, req.(*UpdateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FolderService_DeleteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FolderServiceServer).DeleteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FolderService/DeleteFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FolderServiceServer).DeleteFolder(ctx, req.(*DeleteFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FolderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FolderService",
	HandlerType: (*FolderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFolder",
			Handler:    _FolderService_CreateFolder_Handler,
		},
		{
			MethodName: "GetFolder",
			Handler:    _FolderService_GetFolder_Handler,
		},
		{
			MethodName: "UpdateFolder",
			Handler:    _FolderService_UpdateFolder_Handler,
		},
		{
			MethodName: "DeleteFolder",
			Handler:    _FolderService_DeleteFolder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "folder.proto",
}

func init() { proto.RegisterFile("folder.proto", fileDescriptor_folder_1c0d2e0cd74b2487) }

var fileDescriptor_folder_1c0d2e0cd74b2487 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x5d, 0x37, 0x8a, 0x7b, 0x56, 0x91, 0x57, 0xd1, 0xb2, 0x83, 0x48, 0x4e, 0x9e, 0x7a,
	0x98, 0x82, 0xa7, 0x9d, 0x2c, 0x93, 0x5e, 0x2b, 0xfe, 0x01, 0xad, 0x7b, 0x42, 0x61, 0x36, 0x31,
	0xc9, 0x06, 0x1e, 0x3c, 0xfa, 0x7f, 0x4b, 0x93, 0xae, 0x44, 0xc9, 0x64, 0x83, 0xdd, 0xfa, 0xf2,
	0xf2, 0xbd, 0x2f, 0xef, 0xf7, 0x51, 0x88, 0xde, 0xf8, 0x72, 0x41, 0x32, 0x15, 0x92, 0x6b, 0x8e,
	0x81, 0xa8, 0x98, 0x86, 0x70, 0x6e, 0xce, 0x70, 0x02, 0xc7, 0xb6, 0x9b, 0x67, 0xc9, 0xe0, 0x66,
	0x70, 0x3b, 0x2e, 0xfa, 0x1a, 0xaf, 0x01, 0x24, 0xad, 0x6b, 0x55, 0xf3, 0x26, 0xcf, 0x92, 0xc0,
	0x74, 0x9d, 0x13, 0x44, 0x18, 0x35, 0xe5, 0x3b, 0x25, 0x43, 0xd3, 0x31, 0xdf, 0xed, 0x3c, 0x51,
	0x4a, 0x6a, 0x74, 0x9e, 0x25, 0x23, 0x3b, 0x6f, 0x53, 0xb3, 0x7b, 0x38, 0xb3, 0xae, 0x05, 0x29,
	0xc1, 0x1b, 0x45, 0xc8, 0x20, 0xb4, 0x6e, 0xc6, 0xfb, 0x64, 0x0a, 0xa9, 0xa8, 0xd2, 0xee, 0x4e,
	0xd7, 0x61, 0x5f, 0x10, 0x3f, 0x4a, 0x2a, 0x35, 0x6d, 0xb4, 0x1f, 0x2b, 0x52, 0x1a, 0x2f, 0x21,
	0x5c, 0xa9, 0xfe, 0xd9, 0xc3, 0xa2, 0xab, 0x0e, 0xfe, 0xe8, 0x39, 0x9c, 0x3f, 0x91, 0xde, 0xcd,
	0xdb, 0x85, 0x19, 0xfc, 0x86, 0xc9, 0x3e, 0x21, 0x7e, 0x11, 0x8b, 0x9d, 0xd7, 0xf8, 0x67, 0xd4,
	0xde, 0x2b, 0xe4, 0x10, 0x67, 0xb4, 0xa4, 0x03, 0x58, 0x4f, 0xbf, 0x03, 0x38, 0xb5, 0x53, 0x9e,
	0x49, 0xae, 0xeb, 0x57, 0xc2, 0x19, 0x44, 0x6e, 0x3c, 0x78, 0xd5, 0x46, 0xe8, 0x09, 0x6c, 0x82,
	0x4e, 0xb6, 0x5d, 0xfe, 0xec, 0x08, 0x1f, 0x60, 0xdc, 0xe3, 0xc5, 0x8b, 0xf6, 0xca, 0x5f, 0xda,
	0x5b, 0x84, 0x33, 0x88, 0x5c, 0x9e, 0xd6, 0xd7, 0x43, 0x78, 0xbb, 0xdc, 0x65, 0x62, 0xe5, 0x1e,
	0x4a, 0x7e, 0x79, 0x15, 0x9a, 0x7f, 0xe9, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x74, 0xc4,
	0x51, 0x5b, 0x03, 0x00, 0x00,
}
