// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organization.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Organization struct {
	OrganizationID       int64    `protobuf:"varint,1,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{0}
}
func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (dst *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(dst, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateOrganizationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrganizationRequest) Reset()         { *m = CreateOrganizationRequest{} }
func (m *CreateOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrganizationRequest) ProtoMessage()    {}
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{1}
}
func (m *CreateOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrganizationRequest.Unmarshal(m, b)
}
func (m *CreateOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrganizationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrganizationRequest.Merge(dst, src)
}
func (m *CreateOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrganizationRequest.Size(m)
}
func (m *CreateOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrganizationRequest proto.InternalMessageInfo

func (m *CreateOrganizationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateOrganizationResponse struct {
	Organization         *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateOrganizationResponse) Reset()         { *m = CreateOrganizationResponse{} }
func (m *CreateOrganizationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrganizationResponse) ProtoMessage()    {}
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{2}
}
func (m *CreateOrganizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrganizationResponse.Unmarshal(m, b)
}
func (m *CreateOrganizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrganizationResponse.Marshal(b, m, deterministic)
}
func (dst *CreateOrganizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrganizationResponse.Merge(dst, src)
}
func (m *CreateOrganizationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrganizationResponse.Size(m)
}
func (m *CreateOrganizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrganizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrganizationResponse proto.InternalMessageInfo

func (m *CreateOrganizationResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type GetOrganizationRequest struct {
	OrganizationID       int64    `protobuf:"varint,1,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrganizationRequest) Reset()         { *m = GetOrganizationRequest{} }
func (m *GetOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrganizationRequest) ProtoMessage()    {}
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{3}
}
func (m *GetOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrganizationRequest.Unmarshal(m, b)
}
func (m *GetOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrganizationRequest.Marshal(b, m, deterministic)
}
func (dst *GetOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrganizationRequest.Merge(dst, src)
}
func (m *GetOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrganizationRequest.Size(m)
}
func (m *GetOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrganizationRequest proto.InternalMessageInfo

func (m *GetOrganizationRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

type GetOrganizationResponse struct {
	Organization         *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetOrganizationResponse) Reset()         { *m = GetOrganizationResponse{} }
func (m *GetOrganizationResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrganizationResponse) ProtoMessage()    {}
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{4}
}
func (m *GetOrganizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrganizationResponse.Unmarshal(m, b)
}
func (m *GetOrganizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrganizationResponse.Marshal(b, m, deterministic)
}
func (dst *GetOrganizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrganizationResponse.Merge(dst, src)
}
func (m *GetOrganizationResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrganizationResponse.Size(m)
}
func (m *GetOrganizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrganizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrganizationResponse proto.InternalMessageInfo

func (m *GetOrganizationResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateOrganizationRequest struct {
	Organization         *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateOrganizationRequest) Reset()         { *m = UpdateOrganizationRequest{} }
func (m *UpdateOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrganizationRequest) ProtoMessage()    {}
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{5}
}
func (m *UpdateOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrganizationRequest.Unmarshal(m, b)
}
func (m *UpdateOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrganizationRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrganizationRequest.Merge(dst, src)
}
func (m *UpdateOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrganizationRequest.Size(m)
}
func (m *UpdateOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrganizationRequest proto.InternalMessageInfo

func (m *UpdateOrganizationRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateOrganizationResponse struct {
	Organization         *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateOrganizationResponse) Reset()         { *m = UpdateOrganizationResponse{} }
func (m *UpdateOrganizationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOrganizationResponse) ProtoMessage()    {}
func (*UpdateOrganizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{6}
}
func (m *UpdateOrganizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrganizationResponse.Unmarshal(m, b)
}
func (m *UpdateOrganizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrganizationResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateOrganizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrganizationResponse.Merge(dst, src)
}
func (m *UpdateOrganizationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOrganizationResponse.Size(m)
}
func (m *UpdateOrganizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrganizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrganizationResponse proto.InternalMessageInfo

func (m *UpdateOrganizationResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type DeleteOrganizationRequest struct {
	OrganizationID       int64    `protobuf:"varint,1,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrganizationRequest) Reset()         { *m = DeleteOrganizationRequest{} }
func (m *DeleteOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOrganizationRequest) ProtoMessage()    {}
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{7}
}
func (m *DeleteOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrganizationRequest.Unmarshal(m, b)
}
func (m *DeleteOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrganizationRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrganizationRequest.Merge(dst, src)
}
func (m *DeleteOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOrganizationRequest.Size(m)
}
func (m *DeleteOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrganizationRequest proto.InternalMessageInfo

func (m *DeleteOrganizationRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

type DeleteOrganizationResponse struct {
	Organization         *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteOrganizationResponse) Reset()         { *m = DeleteOrganizationResponse{} }
func (m *DeleteOrganizationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteOrganizationResponse) ProtoMessage()    {}
func (*DeleteOrganizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{8}
}
func (m *DeleteOrganizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrganizationResponse.Unmarshal(m, b)
}
func (m *DeleteOrganizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrganizationResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteOrganizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrganizationResponse.Merge(dst, src)
}
func (m *DeleteOrganizationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteOrganizationResponse.Size(m)
}
func (m *DeleteOrganizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrganizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrganizationResponse proto.InternalMessageInfo

func (m *DeleteOrganizationResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type AddUserToOrganizationRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OrganizationID       int64    `protobuf:"varint,2,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserToOrganizationRequest) Reset()         { *m = AddUserToOrganizationRequest{} }
func (m *AddUserToOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserToOrganizationRequest) ProtoMessage()    {}
func (*AddUserToOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{9}
}
func (m *AddUserToOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserToOrganizationRequest.Unmarshal(m, b)
}
func (m *AddUserToOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserToOrganizationRequest.Marshal(b, m, deterministic)
}
func (dst *AddUserToOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserToOrganizationRequest.Merge(dst, src)
}
func (m *AddUserToOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserToOrganizationRequest.Size(m)
}
func (m *AddUserToOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserToOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserToOrganizationRequest proto.InternalMessageInfo

func (m *AddUserToOrganizationRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AddUserToOrganizationRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

type AddUserToOrganizationResponse struct {
	Organization         *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddUserToOrganizationResponse) Reset()         { *m = AddUserToOrganizationResponse{} }
func (m *AddUserToOrganizationResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserToOrganizationResponse) ProtoMessage()    {}
func (*AddUserToOrganizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{10}
}
func (m *AddUserToOrganizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserToOrganizationResponse.Unmarshal(m, b)
}
func (m *AddUserToOrganizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserToOrganizationResponse.Marshal(b, m, deterministic)
}
func (dst *AddUserToOrganizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserToOrganizationResponse.Merge(dst, src)
}
func (m *AddUserToOrganizationResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserToOrganizationResponse.Size(m)
}
func (m *AddUserToOrganizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserToOrganizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserToOrganizationResponse proto.InternalMessageInfo

func (m *AddUserToOrganizationResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type RemoveUserFromOrganizationRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OrganizationID       int64    `protobuf:"varint,2,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserFromOrganizationRequest) Reset()         { *m = RemoveUserFromOrganizationRequest{} }
func (m *RemoveUserFromOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveUserFromOrganizationRequest) ProtoMessage()    {}
func (*RemoveUserFromOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{11}
}
func (m *RemoveUserFromOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserFromOrganizationRequest.Unmarshal(m, b)
}
func (m *RemoveUserFromOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserFromOrganizationRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveUserFromOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserFromOrganizationRequest.Merge(dst, src)
}
func (m *RemoveUserFromOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveUserFromOrganizationRequest.Size(m)
}
func (m *RemoveUserFromOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserFromOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserFromOrganizationRequest proto.InternalMessageInfo

func (m *RemoveUserFromOrganizationRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *RemoveUserFromOrganizationRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

type RemoveUserFromOrganizationResponse struct {
	Organization         *Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RemoveUserFromOrganizationResponse) Reset()         { *m = RemoveUserFromOrganizationResponse{} }
func (m *RemoveUserFromOrganizationResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveUserFromOrganizationResponse) ProtoMessage()    {}
func (*RemoveUserFromOrganizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_ab0b4e5ae001623e, []int{12}
}
func (m *RemoveUserFromOrganizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserFromOrganizationResponse.Unmarshal(m, b)
}
func (m *RemoveUserFromOrganizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserFromOrganizationResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveUserFromOrganizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserFromOrganizationResponse.Merge(dst, src)
}
func (m *RemoveUserFromOrganizationResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveUserFromOrganizationResponse.Size(m)
}
func (m *RemoveUserFromOrganizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserFromOrganizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserFromOrganizationResponse proto.InternalMessageInfo

func (m *RemoveUserFromOrganizationResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "pb.Organization")
	proto.RegisterType((*CreateOrganizationRequest)(nil), "pb.CreateOrganizationRequest")
	proto.RegisterType((*CreateOrganizationResponse)(nil), "pb.CreateOrganizationResponse")
	proto.RegisterType((*GetOrganizationRequest)(nil), "pb.GetOrganizationRequest")
	proto.RegisterType((*GetOrganizationResponse)(nil), "pb.GetOrganizationResponse")
	proto.RegisterType((*UpdateOrganizationRequest)(nil), "pb.UpdateOrganizationRequest")
	proto.RegisterType((*UpdateOrganizationResponse)(nil), "pb.UpdateOrganizationResponse")
	proto.RegisterType((*DeleteOrganizationRequest)(nil), "pb.DeleteOrganizationRequest")
	proto.RegisterType((*DeleteOrganizationResponse)(nil), "pb.DeleteOrganizationResponse")
	proto.RegisterType((*AddUserToOrganizationRequest)(nil), "pb.AddUserToOrganizationRequest")
	proto.RegisterType((*AddUserToOrganizationResponse)(nil), "pb.AddUserToOrganizationResponse")
	proto.RegisterType((*RemoveUserFromOrganizationRequest)(nil), "pb.RemoveUserFromOrganizationRequest")
	proto.RegisterType((*RemoveUserFromOrganizationResponse)(nil), "pb.RemoveUserFromOrganizationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrganizationServiceClient is the client API for OrganizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrganizationServiceClient interface {
	CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error)
	GetOrganization(ctx context.Context, in *GetOrganizationRequest, opts ...grpc.CallOption) (*GetOrganizationResponse, error)
	UpdateOrganization(ctx context.Context, in *UpdateOrganizationRequest, opts ...grpc.CallOption) (*UpdateOrganizationResponse, error)
	DeleteOrganization(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*DeleteOrganizationResponse, error)
	AddUserToOrganization(ctx context.Context, in *AddUserToOrganizationRequest, opts ...grpc.CallOption) (*AddUserToOrganizationResponse, error)
	RemoveUserFromOrganization(ctx context.Context, in *RemoveUserFromOrganizationRequest, opts ...grpc.CallOption) (*RemoveUserFromOrganizationResponse, error)
}

type organizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrganizationServiceClient(cc *grpc.ClientConn) OrganizationServiceClient {
	return &organizationServiceClient{cc}
}

func (c *organizationServiceClient) CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error) {
	out := new(CreateOrganizationResponse)
	err := c.cc.Invoke(ctx, "/pb.OrganizationService/CreateOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) GetOrganization(ctx context.Context, in *GetOrganizationRequest, opts ...grpc.CallOption) (*GetOrganizationResponse, error) {
	out := new(GetOrganizationResponse)
	err := c.cc.Invoke(ctx, "/pb.OrganizationService/GetOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) UpdateOrganization(ctx context.Context, in *UpdateOrganizationRequest, opts ...grpc.CallOption) (*UpdateOrganizationResponse, error) {
	out := new(UpdateOrganizationResponse)
	err := c.cc.Invoke(ctx, "/pb.OrganizationService/UpdateOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) DeleteOrganization(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*DeleteOrganizationResponse, error) {
	out := new(DeleteOrganizationResponse)
	err := c.cc.Invoke(ctx, "/pb.OrganizationService/DeleteOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) AddUserToOrganization(ctx context.Context, in *AddUserToOrganizationRequest, opts ...grpc.CallOption) (*AddUserToOrganizationResponse, error) {
	out := new(AddUserToOrganizationResponse)
	err := c.cc.Invoke(ctx, "/pb.OrganizationService/AddUserToOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) RemoveUserFromOrganization(ctx context.Context, in *RemoveUserFromOrganizationRequest, opts ...grpc.CallOption) (*RemoveUserFromOrganizationResponse, error) {
	out := new(RemoveUserFromOrganizationResponse)
	err := c.cc.Invoke(ctx, "/pb.OrganizationService/RemoveUserFromOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationServiceServer is the server API for OrganizationService service.
type OrganizationServiceServer interface {
	CreateOrganization(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error)
	GetOrganization(context.Context, *GetOrganizationRequest) (*GetOrganizationResponse, error)
	UpdateOrganization(context.Context, *UpdateOrganizationRequest) (*UpdateOrganizationResponse, error)
	DeleteOrganization(context.Context, *DeleteOrganizationRequest) (*DeleteOrganizationResponse, error)
	AddUserToOrganization(context.Context, *AddUserToOrganizationRequest) (*AddUserToOrganizationResponse, error)
	RemoveUserFromOrganization(context.Context, *RemoveUserFromOrganizationRequest) (*RemoveUserFromOrganizationResponse, error)
}

func RegisterOrganizationServiceServer(s *grpc.Server, srv OrganizationServiceServer) {
	s.RegisterService(&_OrganizationService_serviceDesc, srv)
}

func _OrganizationService_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrganizationService/CreateOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).CreateOrganization(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_GetOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).GetOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrganizationService/GetOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).GetOrganization(ctx, req.(*GetOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_UpdateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).UpdateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrganizationService/UpdateOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).UpdateOrganization(ctx, req.(*UpdateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_DeleteOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).DeleteOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrganizationService/DeleteOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).DeleteOrganization(ctx, req.(*DeleteOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_AddUserToOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).AddUserToOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrganizationService/AddUserToOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).AddUserToOrganization(ctx, req.(*AddUserToOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_RemoveUserFromOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).RemoveUserFromOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrganizationService/RemoveUserFromOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).RemoveUserFromOrganization(ctx, req.(*RemoveUserFromOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrganizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrganizationService",
	HandlerType: (*OrganizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrganization",
			Handler:    _OrganizationService_CreateOrganization_Handler,
		},
		{
			MethodName: "GetOrganization",
			Handler:    _OrganizationService_GetOrganization_Handler,
		},
		{
			MethodName: "UpdateOrganization",
			Handler:    _OrganizationService_UpdateOrganization_Handler,
		},
		{
			MethodName: "DeleteOrganization",
			Handler:    _OrganizationService_DeleteOrganization_Handler,
		},
		{
			MethodName: "AddUserToOrganization",
			Handler:    _OrganizationService_AddUserToOrganization_Handler,
		},
		{
			MethodName: "RemoveUserFromOrganization",
			Handler:    _OrganizationService_RemoveUserFromOrganization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organization.proto",
}

func init() { proto.RegisterFile("organization.proto", fileDescriptor_organization_ab0b4e5ae001623e) }

var fileDescriptor_organization_ab0b4e5ae001623e = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x51, 0x4b, 0x2a, 0x41,
	0x14, 0xc7, 0x5d, 0xaf, 0x08, 0xf7, 0x5c, 0xb9, 0xf7, 0x72, 0x22, 0xd3, 0x29, 0x43, 0x07, 0x12,
	0x9f, 0x0c, 0xac, 0x0f, 0x50, 0x28, 0x45, 0x11, 0x48, 0x53, 0xfb, 0xd2, 0x83, 0xb0, 0xea, 0x21,
	0x84, 0x76, 0x67, 0x9b, 0x5d, 0x7d, 0xe8, 0x8b, 0xf5, 0xf5, 0x62, 0xdd, 0x5a, 0x56, 0x77, 0x46,
	0xa5, 0xa5, 0x37, 0xf5, 0x9c, 0xf3, 0x9b, 0xdf, 0x0c, 0xe7, 0x8f, 0x80, 0x52, 0x3d, 0x3b, 0xde,
	0xec, 0xcd, 0x09, 0x67, 0xd2, 0xeb, 0xfa, 0x4a, 0x86, 0x12, 0x8b, 0xfe, 0x98, 0xdf, 0x42, 0x65,
	0x98, 0xaa, 0x60, 0x1b, 0xfe, 0xa6, 0x3b, 0x6f, 0x06, 0x35, 0xab, 0x69, 0x75, 0x7e, 0x89, 0xb5,
	0x5f, 0x11, 0xa1, 0xe4, 0x39, 0x2e, 0xd5, 0x8a, 0x4d, 0xab, 0xf3, 0x5b, 0x2c, 0x3f, 0xf3, 0x53,
	0xa8, 0xf7, 0x15, 0x39, 0x21, 0xa5, 0x89, 0x82, 0x5e, 0xe7, 0x14, 0x84, 0xc9, 0x80, 0x95, 0x1a,
	0x10, 0xc0, 0x74, 0x03, 0x81, 0x2f, 0xbd, 0x80, 0xf0, 0x1c, 0x2a, 0xe9, 0x43, 0x97, 0x93, 0x7f,
	0x7a, 0xff, 0xbb, 0xfe, 0xb8, 0xbb, 0xd2, 0xbf, 0xd2, 0xc5, 0x2f, 0xa0, 0x7a, 0x4d, 0xa1, 0xce,
	0x60, 0xc7, 0xab, 0xf1, 0x21, 0x1c, 0x64, 0x08, 0xb9, 0x94, 0xee, 0xa1, 0x6e, 0xfb, 0x53, 0xc3,
	0xbb, 0x7c, 0x0f, 0x29, 0x80, 0xe9, 0x90, 0xb9, 0x34, 0xfb, 0x50, 0x1f, 0xd0, 0x0b, 0xe9, 0x35,
	0x77, 0x7d, 0x3c, 0x01, 0x4c, 0x07, 0xc9, 0x25, 0x36, 0x82, 0xa3, 0xcb, 0xe9, 0xd4, 0x0e, 0x48,
	0x3d, 0x4a, 0x9d, 0x5b, 0x15, 0xca, 0xf3, 0x80, 0x54, 0xe2, 0xf4, 0xf9, 0x4d, 0xe3, 0x5c, 0xd4,
	0x3a, 0xdb, 0xd0, 0x30, 0xf0, 0x73, 0x69, 0x4f, 0xa0, 0x25, 0xc8, 0x95, 0x0b, 0x8a, 0xc8, 0x57,
	0x4a, 0xba, 0x3f, 0xe1, 0xfe, 0x04, 0x7c, 0xd3, 0x21, 0x79, 0x2e, 0xd0, 0x7b, 0x2f, 0xc1, 0x5e,
	0xba, 0xfc, 0x40, 0x6a, 0x31, 0x9b, 0x10, 0xda, 0x80, 0xd9, 0xd8, 0x62, 0x23, 0xa2, 0x19, 0xf3,
	0xcf, 0x8e, 0x4d, 0xe5, 0x58, 0x91, 0x17, 0xf0, 0x0e, 0xfe, 0xad, 0xe5, 0x0e, 0x59, 0x34, 0xa4,
	0x8f, 0x33, 0x3b, 0xd4, 0xd6, 0x12, 0x9a, 0x0d, 0x98, 0x4d, 0x48, 0x2c, 0x69, 0x0c, 0x63, 0x2c,
	0x69, 0x0e, 0x56, 0x8c, 0xcd, 0xee, 0x77, 0x8c, 0x35, 0x86, 0x27, 0xc6, 0x9a, 0x63, 0xc1, 0x0b,
	0x38, 0x82, 0x7d, 0xed, 0x0a, 0x62, 0x33, 0x1a, 0xdd, 0xb4, 0xfd, 0xac, 0xb5, 0xa1, 0x23, 0xe1,
	0xbb, 0xc0, 0xcc, 0x6b, 0x82, 0x27, 0x11, 0x62, 0xeb, 0xae, 0xb2, 0xf6, 0xb6, 0xb6, 0xaf, 0xe3,
	0xc6, 0xe5, 0xe5, 0x1f, 0xcc, 0xd9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x5d, 0xf7, 0xf8,
	0x76, 0x06, 0x00, 0x00,
}
